### ISSUE TITLE
A question in make_epsilon_greedy_policy.

### ISSUE THREAD

**Issue by HanfengChi** [dennybritz/reinforcement-learning#114]
why not this?
def policy_fn(observation):
        A = np.ones(nA, dtype=float) * epsilon / (nA-1)
        q_values = estimator.predict(observation)
        best_action = np.argmax(q_values)
        A[best_action] = (1.0 - epsilon)
        return A

**Comment by filipolszewski** [comment]
While the issue might be closed because probabilities *actually sum* up to 1, the method used in solution of MC Control excersise (and not only!) produces **slightly wrong** propabilities. 

For epsilon = 0.01 and 10 actions, best action receives 0.001 + 1.0 - 0.01 = 0.991 and not 0.990 probability. I believe that the code proposed by @HanfengChi gives the correct probs.
