### ISSUE TITLE
Link to "Reinforcement learning book" is broken

### ISSUE THREAD

**Issue by prajjwal1** [dennybritz/reinforcement-learning#122]
The link which has been given in README for 2nd draft of the book seems to be broken. When directed, it gives an error 404. It needs to be fixed.

**Comment by BAILOOL** [comment]
@prajjwal1, this happens because new version of the 'draft' was [published](https://www.reddit.com/r/MachineLearning/comments/7et91d/n_complete_draft_published_reinforcement_learning/) and the link has been modified. I have updated it in the commit stated above. Should be fine if @dennybritz accepts it.

**Comment by prajjwal1** [comment]
You can close it since your commit has been merged.
