### ISSUE TITLE
A3C train.py 

### ISSUE THREAD

**Issue by IbrahimSobh** [dennybritz/reinforcement-learning#26]
Thanks for the great work!

1- I faced an importing error when running train.py
The error was solved after adding **--init--.py** in directory **lib/atari/**     

2- Moreover, I had to upgrade to **TensorFlow 0.11** and **Cuda 8.0** 

3- At the end of train.py "# Wait for all workers to finish": Is this synchronous or asynchronous?  

4- Generally, some variables ended with op, what does "op" stand for?

5- Finally, I am running the training now, some output videos "/tmp/a3c/videos/" seems corrupted and cannot be rendered (and some videos looks fine and rendered)
   
Thanks again

**Comment by dennybritz** [comment]
1. I'm not sure. I should probably re-organize the whole repo so that it's not necessary to adds paths to `sys.path` for the imports. The whole Python module system is somewhat confusing and I'm not sure what the best way to get around this is.

3. It waits synchronously until all async workers are done

4. Operation that is part of the Tensorflow graph. It's standard teminology from Tensorflow.

5. I'm not sure, that hasn't happened to me.
