### ISSUE TITLE
A3C: Safe way to terminate training 

### ISSUE THREAD

**Issue by IbrahimSobh** [dennybritz/reinforcement-learning#44]
What is the safe way to terminate the training (and be able to continue again)? (is Ctrl C safe? or Kill the process)

**Comment by camigord** [comment]
Both options would stop the process. I guess Ctrl C is just nicer. Once the process stops, you will keep the last saved checkpoint. Whenever you continue training, the code should load the last checkpoint and continue from there.

**Comment by IbrahimSobh** [comment]
Thank you

I am very worried that if used any method, then there will ba a chance  that the check point could be corrupted and I can not continue training and lose the model after days of training  

Should I just kill the process any time?

**Comment by camigord** [comment]
Well, ideally you would like to kill the process soon after the last checkpoint is created, so that you do not waste training time... that if you know how often the checkpoints are generated. However, if you decide to kill the process at any point during training, you will only lose the experience collected from the last checkpoint onwards.

**Comment by IbrahimSobh** [comment]
Thank you

So, there is no chance to kill the process during the checkpoint and hence corrupt the checkpoint?

**Comment by camigord** [comment]
The probability of you killing the process exactly while a checkpoint is being created is really small... However, keep in mind that the A3C code is keeping up to 10 checkpoints in disk simultaneously. If, for whatever reason, the last checkpoint gets corrupted, you could always come back to the one before.
